### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by amphineko** [shadowsocks/v2ray-plugin#228]
Hello, I'm making a Dockerfile for this repository. And I would like to contribute and make a pull request.

https://github.com/amphineko/v2ray-plugin-docker/blob/73f7472b4ac831dde3c19a733a9bd8b93702b223/v2ray-plugin/Dockerfile

**Comment by amphineko** [comment]
Also, I'm going to write a `docker-entrypoint.sh` to parse environment variables like `host` or `mode` into plugin option string `tls;host=$TLS_HOST`, to comply the usage like the `shadowsocks/shadowsocks-libev` image.

For example, a `docker-compose.yml` looks like this:
``` yaml
...
    environment:
        METHOD: aes-128-gcm
        PASSWORD: no-password
        PORT: 8388
        V2RAY_HOST: example.com
        V2RAY_PATH: /websocket
...
```
