### ISSUE TITLE
不能启动shadowsocks-libev使用这个插件

### ISSUE THREAD

**Issue by HebronG** [shadowsocks/v2ray-plugin#79]
want start by systemctl
use:
setcap cap_net_bind_service+ep /usr/bin/v2ray-plugin
setcap cap_net_bind_service+ep /usr/bin/ss-server
from other lssues, doesn't work

{
    "server":"0.0.0.0",
    "server_port":80,
    "local_port":****,
    "password":"******",
    "timeout":60,
    "method":"chacha20-ietf-poly1305",
    "mode": "tcp_and_udp",
    "fast_open": true,
    "no_delay": true,
    "reuse_port": true,
    "plugin":"/usr/bin/v2ray-plugin",
    "plugin-opts":"server"
}

● shadowsocks-libev.service - Shadowsocks-libev Default Server Service
   Loaded: loaded (/usr/lib/systemd/system/shadowsocks-libev.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2019-05-11 07:00:27 UTC; 16s ago
     Docs: man:shadowsocks-libev(8)
  Process: 3781 ExecStart=/usr/bin/ss-server -c $CONFFILE $DAEMON_ARGS (code=exited, status=255)
 Main PID: 3781 (code=exited, status=255)

May 11 07:00:27 vultr.guest ss-server[3781]: 2019-05-11 07:00:27 INFO: udp server listening at 149.248.13.145:80
May 11 07:00:27 vultr.guest ss-server[3781]: 2019-05-11 07:00:27 INFO: udp port reuse enabled
May 11 07:00:27 vultr.guest ss-server[3781]: 2019-05-11 07:00:27 INFO: running from root user
May 11 07:00:27 vultr.guest ss-server[3781]: 2019/05/11 07:00:27 V2Ray 4.16 (Po) Custom
May 11 07:00:27 vultr.guest ss-server[3781]: 2019/05/11 07:00:27 A unified platform for anti-censorship.
_**May 11 07:00:27 vultr.guest ss-server[3781]: 2019/05/11 07:00:27 failed to start server: v2ray.com/core/app/proxyman/inbound: failed to listen TCP on 33121 > v2ray.com/core/transport/internet: failed to listen on address:...ss already in use**_
May 11 07:00:27 vultr.guest ss-server[3781]: 2019-05-11 07:00:27 ERROR: plugin service exit unexpectedly
May 11 07:00:27 vultr.guest systemd[1]: shadowsocks-libev.service: main process exited, code=exited, status=255/n/a
May 11 07:00:27 vultr.guest systemd[1]: Unit shadowsocks-libev.service entered failed state.
May 11 07:00:27 vultr.guest systemd[1]: shadowsocks-libev.service failed.

**Comment by liujunhui74** [comment]
plugin-opts => plugin_opts
Dash to underscore.

**Comment by colachg** [comment]
@liujunhui74 It doesn't work.when I write it to command line instead of in json it worked. Is this a bug?
like this:   
` command: ["/usr/bin/ss-server", "-c", "/config/shadowsocks.json", "--plugin-opts", "server;tls;host=mydomain.me"]`

**Comment by liujunhui74** [comment]
> @liujunhui74 It doesn't work.when I write it to command line instead of in json it worked. Is this a bug?
> like this:
> ` command: ["/usr/bin/ss-server", "-c", "/config/shadowsocks.json", "--plugin-opts", "server;tls;host=mydomain.me"]`

In json it is `"plugin_opts":"server;host=example.com`
In command line it is `--plugin-opts="server;host=example.com`
In your command line the arg `--plugin=v2ray` is missing
Either way you can `cat /proc/<v2ray plugin pid>/environ` to get the real opt values.

**Comment by colachg** [comment]
@liujunhui74 Hi, thank you for reply :). I use docker-compose to start the shadowsocks-libev server and mount the binary `v2ray` to `/usr/local/bin/v2ray`.Maybe you can do what I have done to reproduce the problem.
```
version: '3'
services:
  shadowsocks:
container_name: shadowsocks
    restart: always
    privileged: true
    image: shadowsocks/shadowsocks-libev
    ports:
      - 8443:8443
      - 8443:8443/udp
    volumes: 
      - ${PWD}/config:/config
      - ${PWD}/config/v2ray-plugin:/usr/local/bin/v2ray-plugin
        command: ["/usr/bin/ss-server", "-c", "/config/shadowsocks.json", "--plugin", "v2ray-plugin", "--plugin-opts", "server;fast-open;path=/v2ray;host=mydomain.com;loglevel=none"]

```

if you put the last two options in `shadowsock.json`, it will not start correctly. so I put them out of json.
This is my probelm.
Thank you again :)
